### PR TITLE
Use Github Container Repository

### PR DESCRIPTION
**Pull request by flavio-fernandes**
In anticipation to this repo moving... ;)

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@thom311  / @SalDaniele  PTAL

**Comment by SalDaniele** [comment]
LGTM Thanks @flavio-fernandes!

**Comment by thom311** [comment]
Could you please elaborate on the background of this patch? Why do we expect the repo to be moving?

**Comment by flavio-fernandes** [comment]
> Could you please elaborate on the background of this patch? Why do we expect the repo to be moving?

Hi @thom311,
I might be mistaken here, so please feel free to correct me, but I was under the impression that traffic-flow-tests would eventually become part of the ovn-kubernetes umbrella, as the project transitions into its own organization [ [1](https://github.com/cncf/sandbox/issues/111) ]. While this change is still a bit down the road, my current goal is to integrate this fantastic suite as a lane in the ovn-kubernetes pull requests. This way, we can ensure no regressions occur concerning the expected traffic flows that should always function properly [ [2](https://github.com/ovn-org/ovn-kubernetes/issues/4756) ].

[1]: https://github.com/cncf/sandbox/issues/111
[2]: https://github.com/ovn-org/ovn-kubernetes/issues/4756

**Comment by wizhaoredhat** [comment]
@flavio-fernandes Do I need to install "secrets.GITHUB_TOKEN" somehow?

**Comment by SalDaniele** [comment]
For my fork I had to add a new Personal access token to my Github:
- Settings
- Developer Settings
- Personal Access Tokens (opted for classic)

Copy the token and add it as a secret to the repo as we did with quay credentials in the past (Will push a follow-up PR because it seems Github does not like secrets starting with "GITHUB")

**Comment by SalDaniele** [comment]
Actually disregard, I think this secret exists by default.

https://github.com/wizhaoredhat/ocp-traffic-flow-tests/pull/158 should do the trick

**Comment by flavio-fernandes** [comment]
> Actually disregard, I think this secret exists by default.
> 
> #158 should do the trick

TY both!

**Comment by flavio-fernandes** [comment]
I can now `docker pull ghcr.io/wizhaoredhat/ocp-traffic-flow-tests:pr_test`   woot. ;)

**Pull request merged**
