### PR TITLE
[th/bitrate] tftbase: move Bitrate class

### PR DESCRIPTION
**Pull request by thom311**
This will be used later, when already the test run generates the Bitrate result. It will not only be used and known to the Evaluator.

Also, introduce NA (-1) for not available results. For example, TestType.HTTP won't measure the bit rate and it makes no sense.

Also, make it a frozen class and perform strict validation. For convenience, you can pass `int` as tx/rx value, but the constructor will convert them to floats.

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
LGTM

**Comment by wizhaoredhat** [comment]
PTAL @SalDaniele

**Comment by thom311** [comment]
I will rework this patch. Expressing `NA` as `-1.0` is a kludge. It's better to make this an `Optional[float]` and unspecified rates are expressed with `None`. The benefit is that you get an error (from mypy and at runtime) if you try to compare None with a number.

Back on DRAFT.

**Comment by SalDaniele** [comment]
LGTM

**Pull request merged**
